<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Data\BookNook.Data.Models\BookNook.Data.Models.csproj" />
    <ProjectReference Include="..\..\Data\BookNook.Data\BookNook.Data.csproj" />
  </ItemGroup>

</Project>
